Repository ksquareincmx/conference-server, pull requests merged in 2019-01, with the labels that each got.

#23 Feature/pass info dragging to component
  frontend/src/components/Modals/DraggingCalendar/Button.js
  frontend/src/components/Modals/DraggingCalendar/CardContainer.js
  frontend/src/components/Modals/DraggingCalendar/Date.js
  frontend/src/components/Modals/DraggingCalendar/DragginCalendar.js
  frontend/src/components/Modals/DraggingCalendar/ReasonAppointment.js
  frontend/src/components/Modals/DraggingCalendar/Styles.js
  frontend/src/pages/Calendar/Calendar.jsx
Labels: feature

#24 pass booking service to dragging calendar component
  frontend/src/components/Modals/DraggingCalendar/DragginCalendar.js
  frontend/src/pages/Calendar/Calendar.jsx
Labels: feature

#25 Migrated docker integration from the gitlab repo.
  .docker/backend.dockerfile
  .docker/frontend.dockerfile
  .docker/mysql/conf/my.cnf
  .docker/mysql/init/.gitkeep
  .docker/scripts/backend-entrypoint.sh
  .docker/scripts/gulp-install.sh
  .docker/scripts/nginx-latest-image-prerequisites.sh
  .docker/scripts/node-10-image-prerequisites.sh
  .docker/scripts/node-lts-install.sh
  .docker/scripts/wait-for-it.sh
  .docker/scripts/yarn-install.sh
  .env.example
  README.md
  app/config/config.ts
  app/services/GoogleCalendarService.ts
  docker-compose.yml
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/providers/Auth/Auth.jsx
  frontend/src/providers/Booking/Booking.jsx
  frontend/src/providers/Profile/Profile.jsx
  frontend/src/providers/Room/Room.jsx
  frontend/src/providers/User/User.jsx
  frontend/yarn.lock
  package-lock.json
  package.json
Labels: feature

#26 Feature/retrieve reason to appointment dragging component
  frontend/src/components/Modals/DraggingCalendar/DragginCalendar.js
  frontend/src/components/Modals/DraggingCalendar/ReasonAppointment.js
  frontend/src/pages/Calendar/Calendar.jsx
Labels: feature

#31 Fix to `Invalid value {}` when logging in to Google.
  app/controllers/v1/Auth.ts
Labels: bug

#27 create booking clicking the buttom of the dragging calendar
  frontend/config/webpack.config.dev.js
  frontend/config/webpack.config.prod.js
  frontend/src/components/AppointmentCard/Content.js
  frontend/src/components/Modals/DraggingCalendar/Button.js
  frontend/src/components/Modals/DraggingCalendar/DragginCalendar.js
  frontend/src/mappers/AppointmentMapper.js
  frontend/src/pages/Calendar/Calendar.jsx
  frontend/src/pages/Calendar/CalendarPageLogic.js
  frontend/src/pages/Calendar/CalendarStrategy.js
  frontend/src/pages/Calendar/HeaderStrategy.js
  frontend/src/pages/Calendar/Headers/DayHeader.js
  frontend/src/pages/Calendar/Headers/MonthHeader.js
  frontend/src/pages/Calendar/Headers/WeekHeader.js
  frontend/src/pages/Calendar/Headers/YearHeader.js
  frontend/src/pages/Calendar/Utils.js
  frontend/src/pages/Login/Login.jsx
Labels: feature

#34 print appointments to the calendar
  frontend/src/mappers/AppointmentMapper.js
  frontend/src/pages/Calendar/CalendarPageLogic.js
  frontend/src/pages/Calendar/Utils.js
Labels: feature

#37 show user info and status of room
  frontend/src/components/AppointmentCard/BookingList/BookingItem.js
  frontend/src/components/AppointmentCard/BookingList/BookingList.js
  frontend/src/components/AppointmentCard/Content.js
  frontend/src/components/AppointmentCard/RoomList/RoomCard/RoomCard.js
  frontend/src/components/AppointmentCard/RoomList/RoomList.js
  frontend/src/components/Modals/CreateMeeting/AppointmentList.js
  frontend/src/mappers/AppointmentMapper.js
  frontend/src/mappers/RoomMapper.js
  frontend/src/pages/Calendar/Calendar.jsx
  frontend/src/pages/Calendar/CalendarPageLogic.js
Labels: feature

#43 documentation of frontend installation
  README.md
Labels: docs

#45 test configuration
  frontend/package.json
  frontend/src/App.test.js
  frontend/src/setupTests.js
Labels: enhancement
